Updating tests, and fixing the notify task script so it... uh works Now it fails if the subscriber endpoint doesn't return a 200, and it actually checks the SEND_RESULT code appropriately

diff --git a/difftest/expected/notify_subscribers_for_ping b/difftest/expected/notify_subscribers_for_ping
--- a/difftest/expected/notify_subscribers_for_ping
+++ b/difftest/expected/notify_subscribers_for_ping
@@ -1,1 +1,1 @@
-#! /usr/bin/env bash curl "http://services.glgresearch.com/notify/ping/receive" -H 'Content-Type: application/json' --data '{"source":"bottle/ping"}'
+#! /usr/bin/env bash set -e HTTP_STATUS="$(curl --connect-timeout 1 -s -S "http://services.glgresearch.com/notify/ping/receive" -H 'Content-Type: application/json' --data-binary '{"source":"bottle/ping"}' --write-out '%{http_code}')" SEND_RESULT=0 if [ ${SEND_RESULT} -ne 0 -o ${HTTP_STATUS} -ne 200 ]; then if [ -n "https://services.glgresearch.com/notify/send" ]; then if printf "bottle/ping" | grep -E 'bottle\/push\/error'; then # if the message we failed to push is the message indicating a failure to push, we # MUST NOT SEND IT, lest we DoS ourselves : else curl --connect-timeout 1 -s -S "https://services.glgresearch.com/notify/send" -H 'Content-Type: application/json' --data '{"source":"bottle/push/error","notifyUrl":"http://services.glgresearch.com/notify/ping/receive"}' fi fi exit 1 fi
